# Generated by Django 3.2.21 on 2024-12-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='school_year',
        ),
        migrations.AddField(
            model_name='course',
            name='school_year',
            field=models.IntegerField(null=True),
        ),
    ]
