# Generated by Django 3.2.21 on 2024-11-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241124_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
