# Generated by Django 3.2.21 on 2024-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(),
        ),
    ]
