# Generated by Django 5.1.3 on 2024-12-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule_course_alter_courseschedule_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
