# Generated by Django 5.1.3 on 2024-12-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classroom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='status',
        ),
    ]
