from django.urls import path
from .views import AlumnoRetrieveDestroyView, AlumnoRetrieveView, AsistenciaListCreateView, AsistenciaRetrieveDestroyView, AsistenciaRetrieveView, AulaListCreateView, AulaRetrieveDestroyView, AulaRetrieveView, CurriculoListCreateView, CurriculoRetrieveDestroyView, CurriculoRetrieveView, Curso_MatriculaListCreateView, Curso_MatriculaRetrieveDestroyView, Curso_MatriculaRetrieveView, CursoRetrieveDestroyView, CursoRetrieveView, EvaluacionListCreateView, EvaluacionRetrieveDestroyView, EvaluacionRetrieveView, Horario_CursoListCreateView, Horario_CursoRetrieveDestroyView, Horario_CursoRetrieveView, HorarioListCreateView, HorarioRetrieveDestroyView, HorarioRetrieveView, LoginView, MatriculaRetrieveDestroyView, MatriculaRetrieveView, RepresentanteListCreateView, AlumnoListCreateView, CursoListCreateView, MatriculaListCreateView, RepresentanteRetrieveDestroyView, RepresentanteRetrieveView, UserListCreateView

urlpatterns = [
    path('representantes/', RepresentanteListCreateView.as_view(), name='representante-list'),
    path('alumnos/', AlumnoListCreateView.as_view(), name='alumno-list'),
    path('cursos/', CursoListCreateView.as_view(), name='curso-list'),
    path('matriculas/', MatriculaListCreateView.as_view(), name='matricula-list'),
    path('curriculo/', CurriculoListCreateView.as_view(), name='curriculo-list'),
    path('aula/', AulaListCreateView.as_view(), name='aula-list'),
    path('evaluacion/', EvaluacionListCreateView.as_view(), name='evaluacion-list'),
    path('asistencia/', AsistenciaListCreateView.as_view(), name='asistencia-list'),
    path('cursomatricula/', Curso_MatriculaListCreateView.as_view(), name='cursomatricula-list'),
    path('horario/', HorarioListCreateView.as_view(), name='horario-list'),
    path('horariocurso/', Horario_CursoListCreateView.as_view(), name='horariocurso-list'),
    path('users/', UserListCreateView.as_view(), name='user-list-create'),
    path('login/', LoginView.as_view(), name='login'),
    path('representantes/<int:pk>/', RepresentanteRetrieveView.as_view(), name='representante-detail'),
    path('alumnos/<int:pk>/', AlumnoRetrieveView.as_view(), name='alumno-detail'),
    path('cursos/<int:pk>/', CursoRetrieveView.as_view(), name='curso-detail'),
    path('matriculas/<int:pk>/', MatriculaRetrieveView.as_view(), name='matricula-detail'),
    path('curriculo/<int:pk>/', CurriculoRetrieveView.as_view(), name='curriculo-detail'),
    path('aula/<int:pk>/', AulaRetrieveView.as_view(), name='aula-detail'),
    path('evaluacion/<int:pk>/', EvaluacionRetrieveView.as_view(), name='evaluacion-detail'),
    path('asistencia/<int:pk>/', AsistenciaRetrieveView.as_view(), name='asistencia-detail'),
    path('curso_matricula/<int:pk>/', Curso_MatriculaRetrieveView.as_view(), name='curso_matricula-detail'),
    path('horario/<int:pk>/', HorarioRetrieveView.as_view(), name='horario-detail'),
    path('horario_curso/<int:pk>/', Horario_CursoRetrieveView.as_view(), name='horario_curso-detail'),   
    # Rutas para eliminación (DELETE)
    path('representantes/<int:pk>/delete/', RepresentanteRetrieveDestroyView.as_view(), name='representante-delete'),
    path('alumnos/<int:pk>/delete/', AlumnoRetrieveDestroyView.as_view(), name='alumno-delete'),
    path('cursos/<int:pk>/delete/', CursoRetrieveDestroyView.as_view(), name='curso-delete'),
    path('matriculas/<int:pk>/delete/', MatriculaRetrieveDestroyView.as_view(), name='matricula-delete'),
    path('curriculos/<int:pk>/delete/', CurriculoRetrieveDestroyView.as_view(), name='curriculo-delete'),
    path('aulas/<int:pk>/delete/', AulaRetrieveDestroyView.as_view(), name='aula-delete'),
    path('evaluaciones/<int:pk>/delete/', EvaluacionRetrieveDestroyView.as_view(), name='evaluacion-delete'),
    path('asistencias/<int:pk>/delete/', AsistenciaRetrieveDestroyView.as_view(), name='asistencia-delete'),
    path('curso-matriculas/<int:pk>/delete/', Curso_MatriculaRetrieveDestroyView.as_view(), name='curso-matricula-delete'),
    path('horarios/<int:pk>/delete/', HorarioRetrieveDestroyView.as_view(), name='horario-delete'),
    path('horario-cursos/<int:pk>/delete/', Horario_CursoRetrieveDestroyView.as_view(), name='horario-curso-delete'),
]

